fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.25.1"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "4.5.0"
  symlinks:
    aptly: "#{source_dir}"
