fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "3.0.0"
    apt:
      repo: "git://github.com/puppetlabs/puppetlabs-apt.git"
      ref: "1.8.0"
  symlinks:
    aptly: "#{source_dir}"
