name          'gdsoperations-aptly'
version       '0.0.1'
source        'UNKNOWN'
author        'gdsoperations'
license       'MIT'
summary       'UNKNOWN'
description   'UNKNOWN'
project_page  'UNKNOWN'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/apt', '>= 1.0.0'
