name          'gdsoperations-aptly'
version       '0.0.1'
source        'https://github.com/alphagov/puppet-aptly'
author        'gdsoperations'
license       'MIT'
summary       'Module to manage aptly'
description   'aptly is a swiss army knife for Debian repository management'
project_page  'https://github.com/alphagov/puppet-aptly'

dependency 'puppetlabs/stdlib', '>= 3.0.0'
dependency 'puppetlabs/apt', '>= 1.0.0'
